# Generated by Django 4.2.16 on 2024-12-04 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='crytpo_ticker',
            new_name='crypto_ticker',
        ),
    ]
